import parsimony


def generate(key, function, **parameters):
    """Generates the key value using the function and supplied parameters.

    :param key: Parsimony key
    :param function: Callable
    :param parameters: Key value parameters to the function
    :return: value generated by the function
    """
    wrapper = parsimony.configuration.callable_wrapper(key, function, **parameters)
    return wrapper.generate()